server:
  port: 8080
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
    
zuul:
  routes:
    merchandising:
      path: /product/**
      serviceId: merchandising-service
      
          