server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
      
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zwzwapp/config-repo.git                