server:
  port: 8086
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka  
      
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health      